server:
  port: 9999

spring:
  application:
    name: eureka-server

  security:
    user:
      name: eureka-admin
      password: eureka-secret

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    eviction-interval-timer-in-ms: 10000
    enable-self-preservation: false
    renewal-percent-threshold: 0.49

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
    com.banking: DEBUG